
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action PrikazAction;

	private global::Gtk.Action DijagramAction;

	private global::Gtk.Action TablicaAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action AboutAction;

	private global::Gtk.Action PrvaPomoAction;

	private global::Gtk.Action FileAction1;

	private global::Gtk.Action ExitAction;

	private global::Gtk.Action HelpAction1;

	private global::Gtk.Action AboutAction1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.Image image1;

	private global::Gtk.HSeparator hseparator2;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button buttonSave;

	private global::Gtk.Button buttonUpdate;

	private global::Gtk.Button buttonPrikazi;

	private global::Gtk.Button buttonExit;

	private global::Gtk.Table table1;

	private global::Gtk.Calendar calendarDatum;

	private global::Gtk.ComboBox comboboxVrijeme;

	private global::Gtk.Entry entryNapomena;

	private global::Gtk.Entry entryRazina;

	private global::Gtk.Label label1;

	private global::Gtk.Label labelDatum;

	private global::Gtk.Label labelNapomena;

	private global::Gtk.Label labelRazina;

	private global::Gtk.Label labelVrijeme;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.PrikazAction = new global::Gtk.Action("PrikazAction", global::Mono.Unix.Catalog.GetString("Prikaz"), null, null);
		this.PrikazAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Prikaz");
		w1.Add(this.PrikazAction, null);
		this.DijagramAction = new global::Gtk.Action("DijagramAction", global::Mono.Unix.Catalog.GetString("Dijagram"), null, null);
		this.DijagramAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Dijagram");
		w1.Add(this.DijagramAction, null);
		this.TablicaAction = new global::Gtk.Action("TablicaAction", global::Mono.Unix.Catalog.GetString("Tablica"), null, null);
		this.TablicaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Tablica");
		w1.Add(this.TablicaAction, null);
		this.HelpAction = new global::Gtk.Action("HelpAction", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction, null);
		this.AboutAction = new global::Gtk.Action("AboutAction", global::Mono.Unix.Catalog.GetString("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
		w1.Add(this.AboutAction, null);
		this.PrvaPomoAction = new global::Gtk.Action("PrvaPomoAction", global::Mono.Unix.Catalog.GetString("Prva pomoć"), null, null);
		this.PrvaPomoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Prva pomoć");
		w1.Add(this.PrvaPomoAction, null);
		this.FileAction1 = new global::Gtk.Action("FileAction1", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction1, null);
		this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
		w1.Add(this.ExitAction, null);
		this.HelpAction1 = new global::Gtk.Action("HelpAction1", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction1, null);
		this.AboutAction1 = new global::Gtk.Action("AboutAction1", global::Mono.Unix.Catalog.GetString("About"), null, null);
		this.AboutAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
		w1.Add(this.AboutAction1, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("SugarControl");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		global::Gtk.Viewport w2 = new global::Gtk.Viewport();
		w2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menubar1\'><menu name=\'FileAction1\' action=\'FileAction1\'><menui" +
				"tem name=\'ExitAction\' action=\'ExitAction\'/></menu><menu name=\'HelpAction1\' actio" +
				"n=\'HelpAction1\'><menuitem name=\'AboutAction1\' action=\'AboutAction1\'/></menu></me" +
				"nubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.image1 = new global::Gtk.Image();
		this.image1.Name = "image1";
		this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("SugarControl.Sugar Control-SMANJENO2.png");
		this.vbox1.Add(this.image1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.image1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator();
		this.hseparator2.Name = "hseparator2";
		this.vbox1.Add(this.hseparator2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator2]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonSave = new global::Gtk.Button();
		this.buttonSave.WidthRequest = 95;
		this.buttonSave.HeightRequest = 40;
		this.buttonSave.CanFocus = true;
		this.buttonSave.Name = "buttonSave";
		this.buttonSave.UseUnderline = true;
		this.buttonSave.Label = global::Mono.Unix.Catalog.GetString("Save");
		this.hbox1.Add(this.buttonSave);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonSave]));
		w6.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonUpdate = new global::Gtk.Button();
		this.buttonUpdate.WidthRequest = 95;
		this.buttonUpdate.CanFocus = true;
		this.buttonUpdate.Name = "buttonUpdate";
		this.buttonUpdate.UseUnderline = true;
		this.buttonUpdate.Label = global::Mono.Unix.Catalog.GetString("Update/Delete");
		this.hbox1.Add(this.buttonUpdate);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonUpdate]));
		w7.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonPrikazi = new global::Gtk.Button();
		this.buttonPrikazi.WidthRequest = 95;
		this.buttonPrikazi.CanFocus = true;
		this.buttonPrikazi.Name = "buttonPrikazi";
		this.buttonPrikazi.UseUnderline = true;
		this.buttonPrikazi.Label = global::Mono.Unix.Catalog.GetString("Show");
		this.hbox1.Add(this.buttonPrikazi);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonPrikazi]));
		w8.Position = 2;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonExit = new global::Gtk.Button();
		this.buttonExit.CanFocus = true;
		this.buttonExit.Name = "buttonExit";
		this.buttonExit.UseUnderline = true;
		this.buttonExit.Label = global::Mono.Unix.Catalog.GetString("Exit");
		this.hbox1.Add(this.buttonExit);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonExit]));
		w9.Position = 3;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table(((uint)(4)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.calendarDatum = new global::Gtk.Calendar();
		this.calendarDatum.CanFocus = true;
		this.calendarDatum.Name = "calendarDatum";
		this.calendarDatum.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.table1.Add(this.calendarDatum);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.calendarDatum]));
		w11.TopAttach = ((uint)(3));
		w11.BottomAttach = ((uint)(4));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.comboboxVrijeme = global::Gtk.ComboBox.NewText();
		this.comboboxVrijeme.AppendText("");
		this.comboboxVrijeme.AppendText(global::Mono.Unix.Catalog.GetString("Natašte"));
		this.comboboxVrijeme.AppendText(global::Mono.Unix.Catalog.GetString("Prije obroka"));
		this.comboboxVrijeme.AppendText(global::Mono.Unix.Catalog.GetString("Poslije obroka"));
		this.comboboxVrijeme.AppendText(global::Mono.Unix.Catalog.GetString("Prije spavanja"));
		this.comboboxVrijeme.AppendText(global::Mono.Unix.Catalog.GetString("U noći"));
		this.comboboxVrijeme.Name = "comboboxVrijeme";
		this.comboboxVrijeme.Active = 0;
		this.table1.Add(this.comboboxVrijeme);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.comboboxVrijeme]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.LeftAttach = ((uint)(1));
		w12.RightAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entryNapomena = new global::Gtk.Entry();
		this.entryNapomena.CanFocus = true;
		this.entryNapomena.Name = "entryNapomena";
		this.entryNapomena.IsEditable = true;
		this.entryNapomena.InvisibleChar = '●';
		this.table1.Add(this.entryNapomena);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.entryNapomena]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entryRazina = new global::Gtk.Entry();
		this.entryRazina.CanFocus = true;
		this.entryRazina.Name = "entryRazina";
		this.entryRazina.IsEditable = true;
		this.entryRazina.InvisibleChar = '●';
		this.table1.Add(this.entryRazina);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.entryRazina]));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Koristite točku za odvajanje");
		this.table1.Add(this.label1);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
		w15.LeftAttach = ((uint)(2));
		w15.RightAttach = ((uint)(3));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelDatum = new global::Gtk.Label();
		this.labelDatum.Name = "labelDatum";
		this.labelDatum.Xalign = 1F;
		this.labelDatum.LabelProp = global::Mono.Unix.Catalog.GetString("Datum");
		this.table1.Add(this.labelDatum);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.labelDatum]));
		w16.TopAttach = ((uint)(3));
		w16.BottomAttach = ((uint)(4));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelNapomena = new global::Gtk.Label();
		this.labelNapomena.Name = "labelNapomena";
		this.labelNapomena.Xalign = 1F;
		this.labelNapomena.LabelProp = global::Mono.Unix.Catalog.GetString("Napomena");
		this.table1.Add(this.labelNapomena);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.labelNapomena]));
		w17.TopAttach = ((uint)(2));
		w17.BottomAttach = ((uint)(3));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelRazina = new global::Gtk.Label();
		this.labelRazina.Name = "labelRazina";
		this.labelRazina.Xalign = 0F;
		this.labelRazina.LabelProp = global::Mono.Unix.Catalog.GetString("Razina šećera");
		this.table1.Add(this.labelRazina);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.labelRazina]));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelVrijeme = new global::Gtk.Label();
		this.labelVrijeme.Name = "labelVrijeme";
		this.labelVrijeme.Xalign = 1F;
		this.labelVrijeme.LabelProp = global::Mono.Unix.Catalog.GetString("Vrijeme");
		this.table1.Add(this.labelVrijeme);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.labelVrijeme]));
		w19.TopAttach = ((uint)(1));
		w19.BottomAttach = ((uint)(2));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add(this.table1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table1]));
		w20.Position = 4;
		w20.Expand = false;
		w20.Fill = false;
		w2.Add(this.vbox1);
		this.GtkScrolledWindow.Add(w2);
		this.Add(this.GtkScrolledWindow);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 569;
		this.DefaultHeight = 666;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.ExitAction.Activated += new global::System.EventHandler(this.OnExit);
		this.AboutAction1.Activated += new global::System.EventHandler(this.OnAbout);
		this.buttonSave.Clicked += new global::System.EventHandler(this.OnButtonSaveClicked);
		this.buttonUpdate.Clicked += new global::System.EventHandler(this.OnButtonUpdateClicked);
		this.buttonPrikazi.Clicked += new global::System.EventHandler(this.OnButtonPrikaziClicked);
		this.buttonExit.Activated += new global::System.EventHandler(this.OnExit);
		this.buttonExit.Clicked += new global::System.EventHandler(this.OnButtonExitClicked);
		this.entryRazina.TextInserted += new global::Gtk.TextInsertedHandler(this.OnEntryRazinaTextInserted);
	}
}
