
// This file has been generated by the GUI designer. Do not modify.
/*namespace SugarControl
{
	public partial class EvidencijaSecera
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SugarControl.EvidencijaSecera
			this.Name = "SugarControl.EvidencijaSecera";
			this.Title = global::Mono.Unix.Catalog.GetString("EvidencijaSecera");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
*/