
// This file has been generated by the GUI designer. Do not modify.
/*
public partial class UpdatePodataka
{
	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget UpdatePodataka
		this.Name = "UpdatePodataka";
		this.Title = global::Mono.Unix.Catalog.GetString("UpdatePodataka");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 469;
		this.DefaultHeight = 618;
		this.Show();
	}
}*/
